default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hack_key_development
test:
  <<: *default
  database: hack_key_test
  
production:
  <<: *default
  database: hack_key_production
  username: hack_key
  password: <%= ENV['HACK_KEY_DATABASE_PASSWORD'] %>
